global:
  resolve_timeout: 1m
  slack_api_url: ${SLACK_API_URL}

route:
  # Route new alerts to the demo-webhook receiver, defined below
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#cloudops'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
