server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  # - job_name: docker
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: docker
  #         __path__: /var/lib/docker/containers/*/*-json.log
  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           output: log
  #           stream: stream
  #           attrs:
  #     - labels:
  #         stream:
  #     - output:
  #         source: output

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Keycloak specific logs
  - job_name: keycloak
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/keycloak"
        target_label: "container_name"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/keycloak"
        action: keep
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"
      - replacement: "keycloak"
        target_label: "service"
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Scrape system logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
