route:
  # Route new alerts to the demo-webhook receiver, defined below
  receiver: 'slack-notifications'
receivers:
  - name: "cloudops"
  - name: 'slack-notifications'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
      - channel: '#cloudops'
        send_resolved: true
      - title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'

